### PR TITLE
a file

### PR DESCRIPTION
**Pull request by necrosato**
a comment for a file

### CODE REVIEW

**Comment by necrosato** [comment]
AM

**Comment by necrosato** [comment]
This should cause a merge conflict with #4 once its merged in

**Comment by Evyy** [comment]
Does the automerger check that the PR is approved before trying to merge?

**Comment by necrosato** [comment]
@Evyy It should

**Comment by necrosato** [comment]
If I'm not mistaken, right @oliverdain?
Can't tag nick. Maybe he should have permissions hear too?

**Comment by oliverdain** [comment]
Yes, it should require an approve as well as an AM

**Pull request merged**
