### PR TITLE
Naookie/test branch two

### PR DESCRIPTION
**Pull request by necrosato**
A second branch that depends on #3

### CODE REVIEW

**Comment by oliverdain** [comment]
BTW: it looks like the comments came from me but they didn't - the merge bot is using my credentails so...

**Comment by oliverdain** [comment]
AM

**Comment by necrosato** [comment]
AM

**Comment by oliverdain** [comment]
> why did the build fail

@necrosato the build is set up to fail randomly 50% of the time just for testing purposes

**Pull request merged**
